version: '3.1'
services:
  app:
    build:
      context: ./
      args:
        NODE_ENV: development
    volumes:
      - .:/usr/src/app/
    ports:
      - 82:8080
    command: >
      sh -c "npm install && npm run dev"
